# Generated by Django 5.2.7 on 2026-02-08 21:58

import django.db.models.deletion
import my_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('ripple', 'Ripple (XRP)'), ('stellar', 'Stellar (XLM)'), ('usdt', 'Tether (USDT)'), ('bnb', 'BNB (BNB)'), ('bnb_tiger', 'BNB Tiger')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Deposit amount in USD', max_digits=15, null=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Transaction',
                'verbose_name_plural': 'Deposit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement')], max_length=20, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=my_app.models.kyc_document_upload_path)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('technical', 'Technical Support'), ('billing', 'Billing & Payments'), ('account', 'Account Issues'), ('kyc', 'KYC & Verification'), ('trading', 'Trading Support'), ('general', 'General Inquiry')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_user', 'Waiting for User'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='my_app.supportticket')),
            ],
            options={
                'verbose_name': 'Support Reply',
                'verbose_name_plural': 'Support Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('support_ticket', 'Support Ticket'), ('support_reply', 'Support Reply'), ('kyc_update', 'KYC Update'), ('account_update', 'Account Update'), ('deposit_confirmed', 'Deposit Confirmed'), ('general', 'General'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('support_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.supportticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_balance', models.DecimalField(decimal_places=2, default=0, help_text='Bitcoin balance in USD', max_digits=15)),
                ('ethereum_balance', models.DecimalField(decimal_places=2, default=0, help_text='Ethereum balance in USD', max_digits=15)),
                ('ripple_balance', models.DecimalField(decimal_places=2, default=0, help_text='Ripple balance in USD', max_digits=15)),
                ('stellar_balance', models.DecimalField(decimal_places=2, default=0, help_text='Stellar balance in USD', max_digits=15)),
                ('usdt_balance', models.DecimalField(decimal_places=2, default=0, help_text='USDT balance in USD', max_digits=15)),
                ('bnb_balance', models.DecimalField(decimal_places=2, default=0, help_text='BNB balance in USD', max_digits=15)),
                ('bnb_tiger_balance', models.DecimalField(decimal_places=2, default=0, help_text='BNB Tiger balance in USD', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletCopyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('ripple', 'Ripple (XRP)'), ('stellar', 'Stellar (XLM)'), ('usdt', 'Tether (USDT)'), ('bnb', 'BNB (BNB)'), ('bnb_tiger', 'BNB Tiger')], max_length=20)),
                ('wallet_address', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_copy_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Copy Event',
                'verbose_name_plural': 'Wallet Copy Events',
                'ordering': ['-copied_at'],
            },
        ),
    ]
