# Generated by Django 5.2.7 on 2026-02-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_deposittransaction_kycverification_supportticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='ada_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cardano balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='doge_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dogecoin balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='dot_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Polkadot balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='shiba_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shiba Inu balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='solana_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solana balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='trx_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tron balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdc_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='USD Coin balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='xlm_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stellar Lumen balance in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='xrp_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ripple balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='coin_type',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('xrp', 'Ripple (XRP)'), ('solana', 'Solana (SOL)'), ('usdt', 'Tether (USDT)'), ('xlm', 'Stellar Lumen (XLM)'), ('shiba', 'Shiba Inu (SHIB)'), ('usdc', 'USD Coin (USDC)'), ('doge', 'Dogecoin (DOGE)'), ('ada', 'Cardano (ADA)'), ('dot', 'Polkadot (DOT)'), ('trx', 'Tron (TRX)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ripple_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ripple balance in USD (legacy)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='stellar_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stellar balance in USD (legacy)', max_digits=15),
        ),
    ]
